sudo: false

language: ruby
rvm:
  - 2.6

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache: bundler # caching bundler gem packages will speed up build

before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
    # test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
  - ssh -p "$SERVER_PORT" -i ./deploy_key "$SERVER_USER@$SERVER_IP_ADDRESS" pwd

install:
  - gem install bundler jekyll html-proofer

script:
  - bundle install --path vendor/cache
  - bundle exec jekyll build
  #- bundle exec htmlproofer ./_site
  - zip -r site.zip ./_site

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
