# https://taskfile.dev

version: '3'

tasks:
  post:
    vars:
      DATE:
        sh: echo $(date '+%Y-%m')
    cmds:
      - hugo new content/post/{{.DATE}}-{{.CLI_ARGS}}/index.md
      - git add .

  build:
    cmds:
      - rm -rf public/*
      - hugo
      - hugo --config hugo-slides.yaml

  serve:
    cmds:
      - task: build
      - go run main.go

  dev-slides:
    cmds:
      - rm -rf public/*
      - hugo server -D --disableFastRender --config hugo-slides.yaml
